### PR TITLE
Fixes #173: Added the initial UI for Emoji-Heatmapper app

### LINKED ISSUE #173: Create UI for Emoji Heatmapper app
- Issue type: Feature request

### Short description
Add the UI (home page) for the app Emoji Heatmapper.

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Fixes #173 
This is the sample UI of how the emoji heatmapper app will look.
In the next PR, the app will be integrated with the maps part (which will be below the search button -in the part with white box).
test link: https://kavithaenair.github.io/emojiHeatmapper/

**Screenshots for the change:**
image

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by mariobehling** [comment]
Where is the UI of the actual heatmap? Seems like it does not show a map at all. So the core feature is missing. This commit cannot be merged as it does not add an app. Please label it [WIP] in your commit message for now.

Hope to see actual features implemented.

**Comment by kavithaenair** [comment]
@mariobehling Please review
In this PR am able to search for emoji and show it on map with the help of points. The search field is also able to search any query for now. I will be adding validation for search field (able to search only emoji) and rendering the emoji instead of point in the next iteration.
 
Test link: https://kavithaenair.github.io/emojiHeatmapper/   **(Load the scripts to see map)**

image

**Comment by djmgit** [comment]
@kavithaenair please rebase

**Comment by kavithaenair** [comment]
@djmgit @Achint08 @SKrPl  please review

**Comment by daminisatya** [comment]
@mariobehling Click on "load unsafe scripts" to view the changes

**Pull request merged**
