### PR TITLE
fixes #283 - Added loader and error notification to LoklakWordCloud app

### LINKED ISSUE #283: Add loader and error notification to LoklakWordCloud app
Add a loader to indicate that the app is processing a query. Add error notification for empty input.

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #283, added loader to app and also added error notification
for empty input and dates in wrong order.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
Test link: http://loklakapps.surge.sh/LoklakWordCloud/

@Achint08 @singhpratyush @kavithaenair @SKrPl open for review.

**Comment by djmgit** [comment]
@singhpratyush which notifications are failing?

**Comment by singhpratyush** [comment]
I do not get an error notification when I make a request and there is no Internet connection.

**Comment by djmgit** [comment]
@singhpratyush I have handled the net connectivity problem, please re-review.

**Pull request merged**
