### PR TITLE
fixes #208 - Added scaled screen shots

### LINKED ISSUE #208: Images are not ratio across app e.g. whatsTrending in sidebar
Use the same size for app info on different area and ensure all images are scaled in ratio.

As you are using different app info areas, please check where you can reuse the same size several times and ensure images are always scaled properly in ratio, e.g. the app boxes on start screen and the app boxes "similar apps" have a lot of images that are not in ratio, e.g. whatsTrending in sidebar.

screenshot from 2017-06-21 10-11-45

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #208. Added scaled screen shots for

```
College election app
whatsTrending app

```
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
@kavithaenair @SKrPl @Achint08 open for review

**Comment by djmgit** [comment]
Test link : http://loklakapps.surge.sh/

**Comment by djmgit** [comment]
@mariobehling here https://github.com/fossasia/apps.loklak.org/issues/208 you have mentioned about reusing sizes of app info areas, presently there are three app info area in store listing page - get started, app use and others (optional). All of them adapt their size to the size of the content they are holding, I have not forced any particular size upon them. Should I fix there size? In that case if a particular section has very less content then there will be a void space below them and after that the next section will start.

**Comment by kavithaenair** [comment]
@djmgit rebase the branch.

**Comment by mariobehling** [comment]
> you have mentioned about reusing sizes of app info areas

@djmgit This is one option. The important thing is, that the images show up correctly in all areas.

**Comment by djmgit** [comment]
@kavithaenair rebased

**Pull request merged**
