### PR TITLE
Fixes: #286: Added TwitterFollowersInsight App

### LINKED ISSUE #286: Create TwitterFollowersInsight App
- Issue type: Feature request

### Short description
An app in which when we type in a user name or query in the search field, it shows the followers and following people list with their images and they will be clickable, then the query changes and searches for their followers and following, the chain can continue (Followers and Following data will be retrieved using user.json api)

### Would you like to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by kavithaenair**
### Short description
Fixes #286 
Demo link: https://kavithaenair.github.io/TwitterFollowersInsight/

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by kavithaenair** [comment]
@djmgit @vibhcool @singhpratyush Please review.

**Comment by kavithaenair** [comment]
@vibhcool thanks for the suggestions, will work on it. How about creating separate PR for these features?

**Comment by vibhcool** [comment]
yes, sounds good :)

**Comment by mariobehling** [comment]
It is unclear what additional value this app is providing compared to sidebar of loklak.org e.g. here http://loklak.org/search?query=from%3Afossasia

We already have this and you are simply replicating it. Does not make sense.

Please compare existing closed source services and this with your work. Here comparable that would be expected as an outcome of a student in the third term: https://moz.com/followerwonk/analyze/fossasia

Which services have you looked at?

A page with more user information such as followerwonk would make a good app. Right now I see a very rudimentary replicate that would have been great before GSoC.

**Comment by mariobehling** [comment]
Furthermore, you cannot expect your co-developers to follow up on each single point about design and functionality. An app that already sticks to common standards should be provided by you after so much time.

**Comment by kavithaenair** [comment]
@mariobehling Sorry for not making the app up to the mark. I will enhance this app with more features which will provide more information. Thank you.
For now am changing the PR to WIP stage. Will come up with atleast few good features in this PR.

**Comment by kavithaenair** [comment]
@mariobehling @vibhcool Please re-review.

**Comment by djmgit** [comment]
PR looks good, please look into the following problems.

scrol

Some more padding towards the left of the label will look good I guess. It is almost touching the edge.
Also there is nothing in the page right now, yet there is horizontal scroll.

emptyprob

If I enter a name and hit search it shows result. If I do not enter anything it shows popup. Next time when I enter something and hot enter it again shows popup.

**Comment by kavithaenair** [comment]
@djmgit yes, will look into horizontal scroll. But am not able to reproduce the second problem you mentioned.

**Comment by kavithaenair** [comment]
@djmgit Removed the horizontal scroll bar.
image
image

**Comment by djmgit** [comment]
err_there

@kavithaenair the error is there

**steps to reproduce**
* Select the input field and press enter, popup appears
* After the above step, enter something and press enter
* Search happens but the popup appears again

Problem does not occur when button is pressed
When empty input is provided and button is pressed, no popup is shown

**Comment by kavithaenair** [comment]
@djmgit Resolved it. Please review.

**Comment by vibhcool** [comment]
@kavithaenair , Still there are some codacy issues. and branch isn't rebased

**Pull request merged**
