### PR TITLE
Fixes #64 Screenshot error and UI enhancement

### LINKED ISSUE #64: Enhance design with new field design
Please see screenshot below and enhance the design to match the screenshot with different gray areas.

screenshot from 2017-01-11 04-12-06

### PR DESCRIPTION
**Pull request by Marauderer97**
This PR fixes the following:
1. UI changes 
2. Image and link to applist
Fixes #64

### CODE REVIEW

**Comment by jig08** [comment]
@daminisatya ++

**Comment by Marauderer97** [comment]
@jig08 @daminisatya Did the needful

**Comment by daminisatya** [comment]
Great! But The same goes with the PR title too :)

**Comment by Marauderer97** [comment]
@daminisatya do u want me to close this PR and make a fresh one? Because I am not able to edit the PR title.

**Comment by mariobehling** [comment]
@Marauderer97 Thanks for your improvements! Like it.

Maybe you want to do this task next: https://github.com/fossasia/apps.loklak.org/issues/75

Keep it up!

**Pull request merged**
