### PR TITLE
Fixes #43: Changed the URLs hitting the wrong endpoints (Loklak APIs).

### LINKED ISSUE #43: Apps are broken due to wrong endpoint urls.
What i have noticed is : all apps are not able to give response due to the wrong api urls. They all are pointing to "apps.loklak.org"  instead of "api.loklak.org". @mariobehling

### PR DESCRIPTION
**Pull request by KukkadapuSushma**
Fixed the issue for broken URLs pointing to the wrong Endpoints. (CORS issue) Fixed for all the apps which were not working. 

image

### CODE REVIEW

**Comment by KukkadapuSushma** [comment]
@mariobehling Please review.

**Comment by mariobehling** [comment]
$ rake
rake aborted!
Error is:

No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by rhemon** [comment]
@mariobehling I think that is happening because there is no .travis.yml file in the project. Did it have any before?  travis-ci/travis-ci#1000 

I am new to travis-ci (and ci as well) so not quite sure, but I think if we have that file added it should be fine. Or was this travis-ci working fine before without that file? I think it was added recently since this travis check wans't in my PR https://github.com/fossasia/apps.loklak.org/pull/25 Should I create a new issue saying "Add .travis.yml file"?

**Comment by Abhi2424shek** [comment]
@mariobehling @rhemin is correct, Travis checks for the .travis.yml to decide which commands to run and since no file is run it defaults to ruby test cases that's why rake tests are run as per the current source, the .travis.yml file is not found, so we need to fix that to get Travis working.

**Pull request merged**
