### PR TITLE
fixes #179 - added left sidebar to the storelisting page (mobile version)

### LINKED ISSUE #179: Add left navigation sidebar to the mobile version of the store listing page.
Presently there is no left navigation sidebar containing the categories for the mobile version of the site.
Add one to the mobile version.

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #179 - Now the mobile version of the store listing page contains
a drawable left sidebar which can be invoked using a hamburger.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
Test link : http://loklakapps.surge.sh/details.html?q=whatsTrending

screenshot_2017-06-10-16-00-28-591_com android chrome

screenshot_2017-06-10-16-00-35-465_com android chrome

**Comment by djmgit** [comment]
@kavithaenair, @SKrPl , @Achint08 open for review.

**Comment by Achint08** [comment]
@djmgit 
screen shot 2017-06-10 at 3 29 41 am
Look out for this.

**Comment by djmgit** [comment]
small

@Achint08 made changes

**Pull request merged**
