### PR TITLE
Fixes #93 : Added other existing apps to site

### LINKED ISSUE #93: Add other existing apps to site
Please add the following apps and ensure they are working with the service at api.loklak.org

* [x] https://github.com/fossasia/loklak-webtweets (Category: Misc)
* [ ] https://github.com/fossasia/loklak_tweetheatmap (Category: Visualizer)
* [x] https://github.com/fossasia/loklak_movietweets  (Category: Search)
* [ ] https://github.com/fossasia/loklak_heatmap (Category: Visualizer)
* [x] https://github.com/fossasia/loklak_heatmapper (Category: Visualizer)
* [ ] https://github.com/fossasia/loklak_EmojiTracker (Category: Visualizer)

### PR DESCRIPTION
**Pull request by KukkadapuSushma**
Here is the demo  :   https://sushmakukkadapu.github.io/

image

Have added 5 apps. Except the last one : EmojiTracker.

### CODE REVIEW

**Comment by mariobehling** [comment]
I can see, that only http://apps.loklak.org/heatmap works for now. Others not working completely yet.

**Comment by mariobehling** [comment]
Movietweets and webtweets are also working.

**Comment by KukkadapuSushma** [comment]
@mariobehling  ok, i will see through that. And what about "EmojiTracker" (i see that the app is under development)

**Comment by mariobehling** [comment]
Yes, so no need to python apps at the moment. Thanks!

**Pull request merged**
