### PR TITLE
Fixes #77:Hidden top on upscrolling

### LINKED ISSUE #77: Hide top on upscrolling
There is an effect on the web version of the Google app store (https://play.google.com): When the user scrolls up the top bar with the search box gets hidden and the following bar becomes the top bar. Please implement the same on apps.loklak.org. Hide the top bar on scroll up.

### PR DESCRIPTION
**Pull request by KukkadapuSushma**
Here are few screenshots to visualize the change 👍 
Link for demo : https://sushmakukkadapu.github.io/
@daminisatya  @jig08 @mariobehling 

image

.

image

.

image

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check failing tests and provide a test site on your GitHub pages.

**Comment by KukkadapuSushma** [comment]
Test site link : https://sushmakukkadapu.github.io/ @mariobehling

**Comment by mariobehling** [comment]
Thank you.

The move up of the top bar is delayed. I am not sure why. Please implement it without any delay.

**Comment by KukkadapuSushma** [comment]
Yeah sure, @mariobehling will set the delay thing, but before I create a new PR, does this existing PR needs to be merged or cleared? (in order to avoid clash)

**Comment by mariobehling** [comment]
You need to update your branch.

**Comment by KukkadapuSushma** [comment]
@djmgit @jig08 
Thanks for review, I have made changes! Have a look

**Comment by KukkadapuSushma** [comment]
@mariobehling Ok sure I will see through it again.

**Comment by KukkadapuSushma** [comment]
https://sushmakukkadapu.github.io/
@mariobehling  Kindly review!

**Comment by mariobehling** [comment]
Please compare to https://play.google.com and check how you can speed up the feature. Thanks

**Comment by mariobehling** [comment]
Ok, let's speed this up. I am merging this and we can iterate from here. Thank you.

**Comment by KukkadapuSushma** [comment]
Thanks for the merge, will speed up, I have understood after looking thoroughly at  https://play.google.com .

**Pull request merged**
