### PR TITLE
fixes #159 - Loading image is displayed when leader board is reloaded

### LINKED ISSUE #159: Display loading image when the leader board gets reloaded
### Short description
The loader is displayed only once in the leaderboard app, that is when the first search is made. It should also be displayed 
when the leader board is reloaded, that is, when another search is made.

When the leader board is already visible and another search is made, the leader board suddenly updates after some time of inactivity. Instead of this the loading image should be made visible

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #159.Loading image is displayed when leaderboard reloads.
Also empty input is checked and error is shown.

### Short description

**Changes:**

**Screenshots for the change:**

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
test link: http://loklakapps.surge.sh/tweetsleaderboard/

**Comment by djmgit** [comment]
@SKrPl  @kavithaenair open for review

**Comment by kavithaenair** [comment]
The part mentioned in the issue is working fine.But when the page is reloading the column headings are seen near the footer.
As seen in this screenshot:

screenshot 114

**Comment by djmgit** [comment]
@kavithaenair thanks for pointing out, I am fixing it

**Pull request merged**
