### PR TITLE
Added Street Stream App

### PR DESCRIPTION
**Pull request by Elgayar**
Issue #33
I added a tweet search app, however, it shows more tweet details than
other apps, as well as giving the user the ability to interact with that
tweet by liking, retweeting and replying!
As well as the improved responsive design that I made.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please provide a link to the site set up with your working app. Cheers.

**Comment by Elgayar** [comment]
https://elgayar.github.io/apps.loklak.org/streetstream/

However, it's not working and I can't seem to detect the issue, and also no other app is working. On this link and other live links of other users.

**Comment by mariobehling** [comment]
I do not see, that you are using any of the loklak APIs. While many use loklak to display twitter data, a loklak app is an app that uses loklak itself. Am I missing something?

**Comment by Elgayar** [comment]
I see, looks like I missed that :/ I'll work on fixing that.
Can you please in the meantime, review the issue I solved here: #169

**Pull request closed without merging**
