### PR TITLE
Restructured into directories

### PR DESCRIPTION
**Pull request by Marauderer97**
Restructured into directories as discussed with @mariobehling in issue #12

### CODE REVIEW

**Comment by mariobehling** [comment]
Sorry, but I think this is a misunderstanding. The goal is not to re-organize apps into directories, but to re-organize them into categories on the website. See screenshot.

screenshot from 2016-12-26 14-16-07

This PR is not solving it. Therefore closing it.

**Comment by Marauderer97** [comment]
@mariobehling Understood. Sorry for the misunderstanding. So, since they are already some categories, you want me to create the ones that aren't mentioned and remove categories like SUSI API?

**Comment by mariobehling** [comment]
Please follow https://github.com/fossasia/apps.loklak.org/issues/12: lease re-organize the apps into the following categories..

**Comment by Marauderer97** [comment]
@mariobehling I am not able to figure out how to edit the categories, aren't they being fetched from http://loklak.org/api/apps.json, how do I edit this?

**Comment by mariobehling** [comment]
No problem. Take your time to go through the code and you will find a solution. No rush. Cheers.

**Pull request closed without merging**
