### PR TITLE
Fixes #40 : Moved all apps from root directory to apps directory

### LINKED ISSUE #40: All apps in a directory
Personally see all the app folders in root directory seems quite annoying to me, so I think it would be better if these are brought into a single directory. This would make the root directory look simpler and neat.

### PR DESCRIPTION
**Pull request by djmgit**

### CODE REVIEW

**Comment by djmgit** [comment]
@daminisatya  demo link:
https://djmgit.github.io/apps.loklak.org/

**Comment by mariobehling** [comment]
Thank you. Your site works and it makes sense to keep the apps in a subfolder. However the URL structure  also changes. It would make more sense to keep the apps just behind the actual root URL apps.loklak.org/actualapphere instead of apps.loklak.org/apps/actualapphere. "apps.loklak.org/apps/" is not needed as we know already that we are on apps.lokl...

**Comment by djmgit** [comment]
@mariobehling So you are suggesting that the apps should remial in a separate folder but the url should be of the form apps.loklak.org/actualapp.

**Comment by mariobehling** [comment]
> So you are suggesting that the apps should remial in a separate folder but the url should be of the form apps.loklak.org/actualapp.

Yes, I think that would be good.

**Comment by Abhi2424shek** [comment]
@djmgit updates pls.

**Comment by sudheesh001** [comment]
Any updates on this one, it's conflicted. Please resolve conflicts if someone is intending to work on this and open for review.

**Comment by djmgit** [comment]
I am working on this, I will resolve the conflicts and send a PR soon

**Comment by Abhi2424shek** [comment]
@djmgit status? This is a PR? 😊

**Comment by djmgit** [comment]
@Abhi2424shek It has been quite some time I sent this PR, I was busy with some other stuff, I will send new PR soon after making the required changes :)

**Comment by Abhi2424shek** [comment]
Then pls close this, however if you are trying to work from here then pls keep it open and add a WIP to the PR title.

**Comment by djmgit** [comment]
Okay closing it for now

**Pull request closed without merging**
