### PR TITLE
fixes #182 - created an discussion forum for apps.loklak.org

### LINKED ISSUE #182: Create an discussion forum for apps.loklak.org
Create a discussion forum for apps.loklak.org just like we have on others sites where users and developers will be able to comment.

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #182. Created an discussion forum where users
and developers can comment.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
Test link : http://loklakapps.surge.sh/forum.html

@kavithaenair, @Achint08, @SKrPl open for review.

**Comment by daminisatya** [comment]
@djmgit Is the use of disqus expected? @mariobehling

**Comment by djmgit** [comment]
@daminisatya disqus is quite popular as it provides a pluggable comment box without any support from the application's server. Presently I have created the disqus app using my mail ID, if this PR is accepted I can later create a new disqus app with a new mail id and hook it up with apps.loklak.org

**Comment by daminisatya** [comment]
@djmgit Yes we might need some fossasia ID. Check out with @mariobehling if he can provide you one

**Comment by mariobehling** [comment]
Well, I am not sure, if Disqus is the right thing for us, but we can try it out for now.

**Pull request merged**
