### PR TITLE
Moved all the apps to apps directory

### LINKED ISSUE #40: All apps in a directory
Personally see all the app folders in root directory seems quite annoying to me, so I think it would be better if these are brought into a single directory. This would make the root directory look simpler and neat.

### PR DESCRIPTION
**Pull request by djmgit**
Moved all the apps from the root directory to the apps directory.

fixes #40

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check travis is failing. Could you provide a test link to test your changes on your github, please?

**Comment by mariobehling** [comment]
Unfortunately there is a merge conflict. Please help to make this PR run with travis as well.

**Comment by djmgit** [comment]
@daminisatya  okay, I shall send a PR soon

**Comment by mariobehling** [comment]
I am closing this PR as it is a duplicate.

**Pull request closed without merging**
