### PR TITLE
Modified app.json files to change app categories

### PR DESCRIPTION
**Pull request by Marauderer97**
@mariobehling  As suggested in the guide for app contribution, I have made changes in the respective app.json files of the app, so that they belong to the 6 categories listed in #12 but points to be noted:
1. I left boilerplate under Demo category, it din't seem to fit anywhere else
2. I didnot find any games, so no app has the category Game

### CODE REVIEW

**Comment by mariobehling** [comment]
The changes made do not change the categories on the live page.

**Comment by mariobehling** [comment]
Page is still showing former categories and deletion of Susi cause a break in the site.

Please help to finalize the change in categories and Susi.

screenshot from 2017-01-03 15-30-23

Please provide a link to a test set up on your github site in future.

**Comment by Marauderer97** [comment]
@mariobehling This is happening because api.loklak.org is not deployed to the new source.
When I set up locally and use the apps.json file from my local clone of the loklak_server my menu is changed..
image

**Comment by Marauderer97** [comment]
@mariobehling So providing a test link won't help since I am fetching the api from my local host. Should I make an Issue and a PR in loklak_server? Because once merged in loklak_server, the api/apps.json will get updated and the changes will be visible in our frontend too.

**Comment by Marauderer97** [comment]
@mariobehling  would you rather have Accounts API as a category or Accounts? Also should Demo and About Project be separate categories? I was hoping to discuss all these with you before the PR was merged.

**Comment by mariobehling** [comment]
@Marauderer97 Thanks for clearing this up.

The categorization should not depend anymore on the loklak server. Categories should be defined in the apps. How could we achieve this? As this discussion moves away from this specific pull request, let's move this back to https://github.com/fossasia/apps.loklak.org/issues/12. 

Please propose a way to save the category information in the app. Thank you.

**Pull request merged**
