### PR TITLE
fixes #275 - Adding heatmap overlay for CountryTweetMap app

### LINKED ISSUE #275: Add heatmap overlay to CountryTweetMap app
Add heat map overlay to CountryTweetMap app. Add option to add and remove the overlay according to user's choice.

### PR DESCRIPTION
**Pull request by djmgit**
Adding heat map layer.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
Test link: http://loklakapps.surge.sh/CountryTweetMap/

@Achint08 @kavithaenair @SKrPl @vibhcool @open for review :)

**Comment by djmgit** [comment]
@Achint08 the markers give specific data like <Country_code> : <number of tweets>. But the heatmap shows amount of activity at a glance. I have attached each point with an intensity. So points with high number of tweets will have more intense color. Next if we zoom out the map, the heatmap will show clusters of activity area. For example if there are a number of places next to each other with tweet activity then on zooming out the map, user will find a cluster. More the number of adjacent (or close activity regions) brighter will be the color.

**Comment by djmgit** [comment]
@singhpratyush notices the issue, not sure whats the problem, I am using the same co-ordinates as that which I have used for the markers, yet the markers and the heat points are not sharing the same centres.

**Comment by kavithaenair** [comment]
Can you mention the issue corresponding to this @djmgit .

**Comment by djmgit** [comment]
@kavithaenair my bad, I will update this PR ASAP

**Comment by djmgit** [comment]
Heatmap plugin has git some issues with leaflet markers. I am trying to solve this. Closing it for the time being. Will reopen it once I have found out a work around.

**Pull request closed without merging**
