### PR TITLE
Fixes #75 Enhanced topbar

### LINKED ISSUE #75: Enhance top bar to match height and design of loklak.net
At loklak.net the top bar has a different height. Please ensure the height and font size matches on apps.loklak.org.

Also ensure the design of the search box is identical with one difference: Please make the search box at apps.loklak.org shorter and but also include the pink search button.

screenshot from 2017-01-13 16-20-41

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes #75 
Screenshot 
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
Test link: https://marauderer97.github.io/

**Comment by mariobehling** [comment]
Nice work. Please help to implement some small details as well:
* [ ] Make the form of the search bar itself the same as on loklak.net, e.g. no rounded edges and same height
* [ ] Add a thin gray line on the bottom of the menu bar itself
* [ ] Make the same "indent distance" from the left edge of "loklak" as in loklak.net

**Comment by Marauderer97** [comment]
@mariobehling done!

**Comment by jig08** [comment]
@Marauderer97 As @daminisatya pointed it out, squash your commit and we are good to go.

**Comment by Abhi2424shek** [comment]
We could use the merge and squash button guys!

**Comment by Marauderer97** [comment]
@jig08 @daminisatya done :smile:

**Pull request merged**
