### PR TITLE
fixes #146 - Add proper error notification to whatsTrending? app

### LINKED ISSUE #146: Add proper error notification to WhatsTrending? app
Presently there is no error notification implemented, if the user enters anything else apart from date or count number in the filter fields he/she is not shown any error. A proper error should be shown to the user.

### PR DESCRIPTION
**Pull request by djmgit**
Added error notification to whatsTrending app.
Solves issue #146
If user enters anything apart from date or date in
wrong format then user will see error.

### CODE REVIEW

**Comment by djmgit** [comment]
Demo site : http://loklakapps.surge.sh/whatsTrending/

**Comment by kavithaenair** [comment]
@djmgit The issue is not completely fixed , its not verifying the dates given , for instance when we type in such cases :
image

**Comment by djmgit** [comment]
@kavithaenair thanks for pointing it out. Actually I added the issue for checking that the user enters only dates in the date field and number in the count field and the dates are in proper format (YYYY-MM-DD)

**Comment by djmgit** [comment]
Added validation to date

**Comment by kavithaenair** [comment]
@djmgit  still the exception is not handled well. The date field is taking special characters and displaying results. I don't know on what basis are the results generated here.Have a look at the screenshot
image

**Comment by djmgit** [comment]
@kavithaenair my bad, I did a typo in the regex which identifies the date pattern, I have rectified it. I checked out the documentation, until date can be left out, i guess it returns the top trending hashtags from a given date (since) to now (as mentioned there) if until is not mentioned. So I have allowed empty field for until and I have used a default date for start if not provided.

**Comment by mariobehling** [comment]
Please iterate from here. Thanks.

**Pull request merged**
