### PR TITLE
Fixes #133 collegeElection app does not show result when fields are empty

### LINKED ISSUE #133: collegeElections app shows result even when nominee fields are empty
presently on pressing enter or compare button, the app show result even when the nominee fields are blank which should not be the case

### PR DESCRIPTION
**Pull request by djmgit**
… empty

The app now no more shows results when the fields are empty

### CODE REVIEW

**Comment by djmgit** [comment]
Travis failures are mainly due to tab indentation and line length, I am thinking of solving them as a separate issue, as it would increase the size of this PR

**Comment by djmgit** [comment]
@daminisatya okay

**Comment by djmgit** [comment]
@daminisatya fixed the travis errors

**Comment by sudheesh001** [comment]
@jig08 I don't understand how you dismissed an existing review when clearly this is not going to be merged.

**Comment by jig08** [comment]
@sudheesh001 The review by @daminisatya which was dismissed was regarding the failed Travis check.

**Comment by djmgit** [comment]
@jig08 @sudheesh001 @daminisatya squashed the commits

**Comment by sudheesh001** [comment]
Made PR title updates. Looks good. Merging.

**Pull request merged**
