### PR TITLE
changing theme for the apps

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
in reference to the issue #14 @mariobehling 
screenshot from 2016-12-28 00-57-00

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you.

* For the scroll bars, could you leave the color to the standard color of the browser, please?
* The heading "Categories" and "Loklak Apps" please leave them in black/grey

Cheers.

**Comment by nikhilrayaprolu** [comment]
screenshot from 2017-01-01 18-47-51

**Comment by nikhilrayaprolu** [comment]
@mariobehling made the changes

**Comment by mariobehling** [comment]
Please set up the site on your Github repo and provide a link here. Thank you.

**Comment by nikhilrayaprolu** [comment]
@mariobehling https://nikhilrayaprolu.github.io/apps.loklak.org/

**Comment by mariobehling** [comment]
Some apps do not have they styles anymore. Please check, e.g. compare http://apps.loklak.org/userprofile/ and https://nikhilrayaprolu.github.io/apps.loklak.org/userprofile/

**Comment by nikhilrayaprolu** [comment]
@mariobehling  I made the required changes to my gh-pages you can look at it

**Comment by nikhilrayaprolu** [comment]
@daminisatya squashed into a single commit

**Comment by jig08** [comment]
@nikhilrayaprolu There still exist two commits. Also rename the squashed commit as `Fixes #<issue number>: <commit message>`

**Pull request merged**
