### PR TITLE
Adding JSON file for app list

### PR DESCRIPTION
**Pull request by Marauderer97**
Solves #12 
Two points to be noted, 
Firstly,The json file created here is static, and does not automatically get updated like in loklak_sever on new app creation. Loklak_server used Java for this, and since I only have beginner skills in it, I was not able to find a way to duplicate it here
Secondly,I also rectified a minute error in a category name(Internet of things), and all apps previously under Accounts API or Accounts are now under Accounts.
This is how the site looks now:
image
P.S : If this PR is satisfactory, I will make the necessary updates in the Documentation(README file)

### CODE REVIEW

**Comment by Marauderer97** [comment]
Working link:
https://marauderer97.github.io

**Comment by mariobehling** [comment]
Thank you.

**Comment by mariobehling** [comment]
Did not seem to solve it on the current site yet, or it is still in cache of cloudflare. Please check http://apps.loklak.org/

**Comment by Marauderer97** [comment]
Strange, it works on my setup, and in my github link too, looking into this

**Comment by Marauderer97** [comment]
@mariobehling was a minute error with the html file, an id was removed while making changes to the site design. Please see PR #36 . Thanks!

**Pull request merged**
