### PR TITLE
fiixes #109 - fixed account apps

### PR DESCRIPTION
**Pull request by djmgit**
fixed the following  apps:

signup app
login app
register public key app
password recovery app
view permissions app
reset password app(not tested)

### CODE REVIEW

**Comment by djmgit** [comment]
demo link : http://loklakapps.surge.sh/

**Comment by djmgit** [comment]
the password reset app is not tested as I am not sure how to generate token.
However I have fixed the api calling by using jsonp

**Comment by yukiisbored** [comment]
Typo on commit message, please change it and pleae do test the reset password app, you can test it by running a local instance of loklak or request someone else to test it. Don't put the "not tested" on the commit message.

**Comment by djmgit** [comment]
@yukiisbored I have a local instance of the server running. I tried calling the api on the local server, but its giving error : token not specified .

**Comment by mariobehling** [comment]
Let's merge and iterate.

@djmgit Please open an issue for the remaining.

**Pull request merged**
