### PR TITLE
fixes #163 - Added footer

### LINKED ISSUE #163: Create a footer
### Short description
Presently there is no footer in the main page.So if a user goes to the bottom of the page and wants to visit the links like api, blog etc then he/she would have to again scroll up. So it would be nice if there is a footer with those links.

### PR DESCRIPTION
**Pull request by djmgit**
### Short description
Fixes issue #163. The main page now contains a footer.

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
test link: http://loklakapps.surge.sh/

@SKrPl @kavithaenair open for review

**Comment by mariobehling** [comment]
Footer no longer visible on test page.

**Comment by kavithaenair** [comment]
As @mariobehling said, the test link is not showing the footer anymore. @djmgit please look it into.

**Comment by djmgit** [comment]
@kavithaenair I have removed it, due to some glitches, I am working on it, will update the PR ASAP

**Comment by djmgit** [comment]
@kavithaenair @Achint08 @SKrPl updated my PR

**Comment by djmgit** [comment]
@hemantjadon sure, I will fix it.

**Comment by djmgit** [comment]
@hemantjadon updated PR

**Comment by singhpratyush** [comment]
@djmgit: The changes look good. Please resolve conflicts and rebase.

**Comment by hemantjadon** [comment]
@djmgit Is the link also updated? I dont think it is, It is still showing moving footer.
screen shot 2017-06-23 at 5 49 00 pm

**Comment by djmgit** [comment]
@hemantjadon strange!! I have updated the link, I tested it on chrome and firefox, the footer is not appearing in the middle, even if it appears (is some one scrolls the page while loading), it appears right at the bottom. Which browser are you using? Could you please also test the details page?

**Comment by SKrPl** [comment]
@djmgit There are some merge conflicts, and I also can't see footer in both homepage and app's details page.

**Comment by hemantjadon** [comment]
@djmgit Am I checking the wrong link?  http://loklakapps.surge.sh/
The footer is still starting in the mid.

**Comment by djmgit** [comment]
@hemantjadon yeah,  that is the current link, which browser are you using??

**Comment by hemantjadon** [comment]
@djmgit I am using Chrome 59

**Comment by Achint08** [comment]
@djmgit It is even blinking for me. OSX Firefox.

**Comment by djmgit** [comment]
Okay, I guess this is due to compatibility issues across various browsers. Closing it for now, will be working on it later.

**Pull request closed without merging**
