### PR TITLE
fixes #222 - updated app.json of majority of the apps

### LINKED ISSUE #222: Update app.json of existing apps to display additional elements
Update the existing apps' app.json file to include the additional elements added here : https://github.com/fossasia/apps.loklak.org/pull/211

### PR DESCRIPTION
**Pull request by djmgit**
fixes issue #222. Updated app.json of most of the apps to
display the elements added in pr #209

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
- [x] There is only strictly only one commit per issue.

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by djmgit** [comment]
test link - loklakapps.surge.sh/

@kavithaenair @SKrPl @Achint08 @hemantjadon open for review

open loklakapps.surge.sh/ , select any of the following apps 
```
dcuphanduy
movietweets
yasoob
fossasia-histogram
yathannsh
KnowTheDiff
userprofile
LQL
webtweets
tweetsleaderboard
bolerplate
collegeElections
social-wall
querybrowser
superwomen7
histogram
sentimentVisualizer
oneClickDeploy
tweetfeed

```
and scroll down to find the newly added elements (version, updated, etc)

**Comment by djmgit** [comment]
@kavithaenair The idea is to maintain a list of contributors for each app, whenever some one contributes to an app he or she can update the app.json and insert his/her name in the contributors list. As there are a lot of apps and I do not know who contributed to them so presently I have used authors name as the only entry in the contributors list.
Ofcourse the updation part will be mentioned in tutorial soon.

**Comment by kavithaenair** [comment]
Rebase the branch, rest looks good to me @djmgit. 👍

**Comment by djmgit** [comment]
@kavithaenair rebased

**Comment by kavithaenair** [comment]
@djmgit Ask others to review by mentioning in the group and rebase it. This PR is good to go but still is open since 3 days.

**Comment by djmgit** [comment]
@kavithaenair @SKrPl @Achint08 @hemantjadon @singhpratyush @vibhcool @SarishiNoHara rebased, please review

**Comment by vibhcool** [comment]
nice PR 👍 
I have a question that isn't related to the issue, could we replace this `Visit developer's website` by something else like a link with author's name. 
I think it would look better.

**Comment by djmgit** [comment]
@vibhcool sounds good, I will open an issue for this.

**Pull request merged**
