### PR TITLE
Fixes #28: Solves categories bug

### LINKED ISSUE #28: The categories aren't working
screen shot 2017-01-05 at 10 54 23 am
screen shot 2017-01-05 at 10 54 16 am

If someone clicks on a category, it won't work.

I would like to work on this.

### PR DESCRIPTION
**Pull request by Heredroky**
This PR solves #28 

I hope you like.

Cheers! 😄

### CODE REVIEW

**Comment by Marauderer97** [comment]
@Heredroky  This is happening because we are trying to change the category options and trying to get apps.loklak.org to have it's own api/apps.json generation. Once that is integrated, the links will be fixed automatically.
Cheers! :smile:

**Comment by Heredroky** [comment]
@Marauderer97 Hmm, then.... should I close this?

**Comment by mariobehling** [comment]
@Marauderer97 @daminisatya What is the timeline? Maybe no need for the hack here, if we can go ahead quickly.

**Comment by Heredroky** [comment]
@mariobehling Should this be closed?

**Comment by Heredroky** [comment]
@mariobehling If you merge this PR, the #32 Will be fixed

## Before: 
screen shot 2017-01-06 at 12 55 06 pm
## After: 
screen shot 2017-01-06 at 12 54 29 pm

----------------

## Before:
screen shot 2017-01-06 at 12 55 20 pm

## After:
screen shot 2017-01-06 at 12 57 52 pm

- [ ] It is responsive, the rows are responsive
- [ ] The user can see the menu
- [ ] The info of the app is show correctly

It totally worked locally, and I'm sure that it will work in the webpage, please trust me,

Cheers 😄

**Comment by Heredroky** [comment]
@mariobehling Please check this

**Comment by mariobehling** [comment]
Thanks, could you take my comment from this issue into account, please:
https://github.com/fossasia/apps.loklak.org/issues/13#issuecomment-271022355

I see you are still improving "loklak apps" and other areas, that are actually redundant. Therefore please have a look at the issue #13.

Thank you.

**Comment by Heredroky** [comment]
@mariobehling I don't think that the responsive design is redundant, besides, the PR fixes a bug in the descriptions of the apps

**Comment by mariobehling** [comment]
screenshot from 2017-01-06 23-17-55

Please take out "Categories" on left and "Loklak Apps" in the main area. We can also take inspiration from the Google Apps store, but in a simplified way.

**Comment by Heredroky** [comment]
@mariobehling I told you that if that "label" is taken out from there, it won't work

**Comment by Heredroky** [comment]
@mariobehling At least, merge this as a progress

**Comment by Heredroky** [comment]
@mariobehling I am waiting for your answer

**Comment by mariobehling** [comment]
Thanks. Please resolve merge conflicts.

**Comment by Heredroky** [comment]
@mariobehling I resolved the merge conflicts, can it be merged now?

**Comment by Heredroky** [comment]
@mariobehling Please merge it, I have been waiting a day 😞

**Comment by Abhi2424shek** [comment]
Please try to understand @Heredroky be good here I know you are but you should be much more better, please be patient and fix as stated by Mario sir.

**Comment by Abhi2424shek** [comment]
Please understand that mentors are having their own tasks in life they take open source in their free time so pls feel free to wait...

**Comment by Abhi2424shek** [comment]
@Heredroky till then it would be nice to squad your images

**Comment by Heredroky** [comment]
@Abhi2424shek I know that, and I have been respectful.

**Comment by Abhi2424shek** [comment]
Yep just mentioned to wait a bit bro ;) :)

**Comment by Heredroky** [comment]
@mariobehling BTW, I can't squash the 2 last commits

**Comment by mariobehling** [comment]
Thanks everyone. Just had a nice lunch ;-)

Let's iterate then and do the next improvements in following PRs. 

Thank you for all your effort!

**Pull request merged**
