### PR TITLE
Improved design

### LINKED ISSUE #51: Improve design
* [x] Use same size and design for top left loklak icon as on http://loklak.net seach pages and use Courier New as a font
* [x] Use loklak in pink and apps in standard black color of top menu bar (not in capital letters)
* [x] Always write loklak in small (not capital letters) using Courier New
* [x] Link the top left loklak apps link to "./" home of the service (not loklak.org)
* [x] Implement top right menu bar items as follows (in same order)
  * [x] Home -> link to home of service
  * [x] Search -> http://loklak.net
  * [x] About -> http://loklak.net/about
  * [x] Blog -> http://blog.loklak.net
  * [x] Developers -> http://dev.loklak.org
  * [x] API -> http://api.loklak.org
* [x] On the left sidebar use the same gray color as on the top bar
* [ ] On the left sidebar ensure no item stays on with a gray background and blue link color

### PR DESCRIPTION
**Pull request by djmgit**
Improved design of the site

fixes #51

### CODE REVIEW

**Comment by jig08** [comment]
Before/after screenshots and demo link pls ?

**Comment by djmgit** [comment]
before making changes
old

after making changes
new

**Comment by djmgit** [comment]
demo link :
https://djmgit.github.io/apps.loklak.org/

**Comment by jig08** [comment]
See to the failing TravisCI build pls.

**Comment by mariobehling** [comment]
Thanks! I am merging, but the issue is not yet entirely solved. So, let's iterate step by step. The blue link on the left sidebar is still there.

screenshot from 2017-01-10 00-12-07

**Comment by djmgit** [comment]
@mariobehling The blue links are not appearing in firefox, but they are appearing in chrome.
I looking into it.

**Comment by Marauderer97** [comment]
@djmgit I think you need to edit bootstrap.min.css, when a:hover and a:focus is applied, the text color is set to blue.. somewhere around line 5. Cheers! :)

**Pull request merged**
